config/routes.rb
Crowdhoster::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # PAGES
  root                                         to: 'pages#index'

  # USERS
  devise_for :users, { path: 'account' }
  devise_scope :user do
    match '/user/settings',                    to: 'devise/registrations#edit',             as: :user_settings
  end

  # ADMIN
  get '/admin',                                to: 'admin#admin_dashboard',                 as: :admin_dashboard
  match '/admin/homepage',                     to: 'admin#admin_homepage',                  as: :admin_homepage
  match '/admin/site-settings',                to: 'admin#admin_site_settings',             as: :admin_site_settings
  match '/admin/customize',                    to: 'admin#admin_customize',                 as: :admin_customize
  namespace :admin do
    resources :campaigns
    post '/payments/:id/refund',               to: 'payments#refund_payment',               as: :admin_payment_refund
  end

  match '/admin/campaigns/:id/copy',           to: 'admin/campaigns#copy',                  as: :admin_campaigns_copy
  match '/admin/campaigns/:id/payments',       to: 'admin/campaigns#payments',              as: :admin_campaigns_payments
  match '/admin/processor-setup',              to: 'admin#admin_processor_setup',           as: :admin_processor_setup
  post '/admin/bank-setup',                    to: 'admin#create_admin_bank_account',       as: :create_admin_bank_account
  get '/admin/bank-setup',                     to: 'admin#admin_bank_account',              as: :admin_bank_account
  delete '/admin/bank-setup',                  to: 'admin#delete_admin_bank_account',       as: :delete_admin_bank_account
  match '/admin/notification-setup',           to: 'admin#admin_notification_setup',        as: :admin_notification_setup
  match '/ajax/verify',                        to: 'admin#ajax_verify',                     as: :ajax_verify

  # CAMPAIGNS
  match '/:id/checkout/amount',                to: 'campaigns#checkout_amount',             as: :checkout_amount
  match '/:id/checkout/payment',               to: 'campaigns#checkout_payment',            as: :checkout_payment
  match '/:id/checkout/process',               to: 'campaigns#checkout_process',            as: :checkout_process
  match '/:id/checkout/confirmation',          to: 'campaigns#checkout_confirmation',       as: :checkout_confirmation
  post '/:id/checkout/error',                  to: 'campaigns#checkout_error',              as: :checkout_error
  match '/:id',                                to: 'campaigns#home',                        as: :campaign_home
  match '/:id/ajax/create_payment_user',        to: 'campaigns#ajax_create_payment_user',    as: :ajax_create_payment_user


  namespace :api, defaults: {format: 'json'} do
    scope module: :v0  do
      resources :campaigns, only: :show do
        resources :payments, only: :index
      end
    end
  end
end

app/views/admin/_breadcrumbs.html.erb
<% crumbs_arr = [['Admin', admin_dashboard_path]] + (crumbs ||= []) %>
<h3>
  <%= raw(crumbs_arr.map {|crumb| link_to crumb[0], crumb[1] }.join(" > ")) %>
  <span class="loader" data-loader="admin_header" style="display:none"></span>
</h3>

app/views/admin/_footer.html.erb
<div id="admin-footer">
  <div class="container clearfix">
    <p class="pull-right">© 2014 Tilt.com</p>
  </div>
</div>

app/views/admin/_header.html.erb
<%= render 'admin/breadcrumbs', crumbs: @breadcrumbs %>

<ul class="nav nav-pills">
  <li class="<%= 'active' if active == 'campaigns' %>">
    <%= link_to "Campaigns", admin_campaigns_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
  </li>
  <li class="<%= 'active' if active == 'homepage' %>">
    <%= link_to "Homepage", admin_homepage_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
  </li>
  <li class="<%= 'active' if active == 'customize' %>">
    <%= link_to "Customize", admin_customize_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
  </li>
  <li class="dropdown<%= " active" if active == "settings" %>">
    <a class="dropdown-toggle"
       data-toggle="dropdown"
       href="#">
        Settings
        <b class="caret"></b>
      </a>
    <ul class="dropdown-menu">
      <%= link_to "Site Settings", admin_site_settings_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
      <%= link_to "Payment Settings", admin_processor_setup_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
      <%= link_to "Notification Settings", admin_notification_setup_path, :class => 'show_loader', :'data-loader' => "admin_header" %>
    </ul>
  </li>
</ul>

app/views/admin/admin_bank_account.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'settings' %>

    <ul class="nav nav-tabs nav-bank-setup">
      <li><a href="<%= admin_processor_setup_path %>">Payment Processor</a></li>
      <li class="active"><a href="<%= admin_bank_account_path %>">Bank Setup</a></li>
    </ul>

  <div id="admin_bank_setup">

    <div class="main_content">

      <% if @bank['is_default'] %>

      <h4>Your banking information's all set up!</h4>
      <div class="account_numbers">
        <p>Routing Number: ****<%= @bank['bank_code_last_four'] %></p>
        <p>Account Number: ****<%= @bank['account_number_last_four'] %></p>
      </div>
      <div class="more_info">
        <p>Campaign funds are transferred automatically to your account within 2 business days of campaign expiration. </p>
        <p>Need to change your bank account? <%= link_to 'Delete bank account', delete_admin_bank_account_path, :confirm => 'Are you sure you want to delete this bank account?', :method => :delete %></p>
      </div>

      <% else %>

      <%= form_tag(create_admin_bank_account_path, method: "post", id: "admin_bank_form") %>

      <h4>Personal Information <span class="label show_tooltip" data-placement="right" data-title="BUSINESS ACCOUNTS: <br>To prevent fraud, we verify your personal identity independently of your business bank account. <br> DO NOT ENTER YOUR BUSINESS ADDRESS / PHONE. Please enter your personal details here and your business account routing and account numbers in the 'Banking Information' section below.">Using a business account?</span></h4>
      <fieldset>

          <div class="form-row clearfix">
            <div class="field">
              <label for="full_legal_name">Legal Name (first and last)</label>
              <input name="full_legal_name" id="full_legal_name" type="text">
            </div>

            <div class="field">
              <label for="phone">Phone (XXX-XXX-XXXX)</label>
              <input name="phone" id="phone" type="text">
            </div>
          </div>

          <div class="form-row clearfix">
            <div class="field">
              <label for="street_address">Street Address</label>
              <input name="street_address" id="street_address" type="text" style="width: 320px">
            </div>

            <div class="field">
              <label for="zip">Zip Code</label>
              <input name="zip" id="zip" type="text" style="width: 100px">
            </div>
          </div>

          <div class="form-row clearfix">
            <div class="field">
            <label>Birth Month</label>
              <select id="birth_month" style="width: 110px">
                  <option value="01" selected>January</option>
                  <option value="02">February</option>
                  <option value="03">March</option>
                  <option value="04">April</option>
                  <option value="05">May</option>
                  <option value="06">June</option>
                  <option value="07">July</option>
                  <option value="08">August</option>
                  <option value="09">September</option>
                  <option value="10">October</option>
                  <option value="11">November</option>
                  <option value="12">December</option>
              </select>
            </div>

            <div class="field">
              <label for="birth_year">Birth Year (YYYY)</label>
              <input name="birth_year" id="birth_year" type="text" style="width: 100px">
            </div>
          </div>

        </fieldset>

        <h4>Banking Information</h4>
        <fieldset>
          <div class="form-row clearfix">
            <div class="field">
              <label for="routing_number">Routing Number <i class="icon icon-info-sign show_tooltip" data-placement="right" data-title="Your routing number is the nine digit number in the bottom left corner of your check."></i></label>
              <input name="bank_routing_number" id="bank_routing_number" type="text">
            </div>

            <div class="field">
              <label for="account_number">Account Number <i class="icon icon-info-sign show_tooltip" data-placement="right" data-title="Your account number is the number to the right of the routing number on your check."></i></label>
              <input name="account_number" id="account_number" type="text">
            </div>
          </div>
        </fieldset>

        <input id="ct_user_id" type="hidden"  name="ct_user_id" value="<%= @ct_admin_id %>" >

        <button class="btn btn-primary show_loader" data-loader="bank_form" type="submit">Save</button>
        <span class="loader" data-loader="bank_form" style="display:none"></span>
      </form>
      <div id="errors"></div>

      <% end %>

    </div>

    <div class="settlements">

    </div>

  </div>
  </div>
</div>

<%= javascript_include_tag "https://api.crowdtilt.com/v1/js/crowdtilt.js" %>
<%= javascript_tag do %>
  crowdtilt.init('<%= Rails.env.production? ? 'production' : 'sandbox' %>')
<% end %>

app/views/admin/admin_customize.html.erb
<div id="admin">
  <div class="container content_box clearfix">

    <%= render 'admin/header', active: 'customize' %>

    <div id="admin_customize">

      <%= form_for(@settings, url: admin_customize_path, multipart: true, html: { id: "admin_customize_form" }) do |f| %>

        <fieldset>
          <legend class="foldable"><a>Customize</a></legend>
          <div class="foldable default_expanded" id="customize_tools">

            <div class="field clearfix">
              <p class="explanation">Add your own CSS styles to fully customize the look and feel of your site.</p>
              <div id="settings_custom_css_alert" class="alert alert-danger inline-alert" style="display:none;" ></div>
              <label>Custom CSS</label>
              <%= f.text_area :custom_css, rows: 3, style: "width:400px; height: 200px", :placeholder => "#campaign #funding_area { background: white; }" %>
            </div>

            <div class="field clearfix">
              <p class="explanation">Add your own JavaScript here. Use this field to paste in scripts for analytics tracking, retargeting, etc.</p>
              <div id="settings_custom_js_alert" class="alert alert-danger inline-alert" style="display:none;" ></div>
              <label>Custom JavaScript</label>
              <%= f.text_area :custom_js, rows: 3, style: "width:400px; height: 200px", :placeholder => "<script> CODE </script>" %>
            </div>

          </div>
        </fieldset>

        <div id="settings_custom_alert" class="alert alert-danger box-alert" style="display:none;" ></div>
        <%= f.submit "Save", :'class' => "btn btn-primary show_loader", :'data-loader' => "project_form" %>
        <span class="loader" data-loader="project_form" style="display:none"></span>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/admin_homepage.html.erb
<div id="admin">
  <div class="container content_box clearfix">

    <%= render 'admin/header', active: 'homepage' %>

    <div id="admin_homepage">

      <%= form_for(@settings, url: admin_homepage_path, multipart: true, html: { id: "admin_homepage_form" }) do |f| %>

        <fieldset>
          <legend class="foldable"><a>Homepage Content</a></legend>

          <div class="foldable default_expanded">
            <div class="field clearfix">
              <p class="explanation inline">This content is shown on the homepage in addition to the campaign titles.</p>
              <%= f.cktext_area :homepage_content %>
            </div>
          </div>

        </fieldset>

        <fieldset>
          <legend class="foldable"><a>Sharing Details</a></legend>

          <div class="foldable default_expanded">
            <div class="field clearfix">
              <p class="explanation">This is the default text that will be used for the tweet button.</p>
              <label>Tweet Text</label>
              <%= f.text_area :tweet_text, rows: 2 %>
            </div>

            <div class="field clearfix">
              <p class="explanation">The title shown when your site is shared via Facebook. Leave this blank if you want to use your project name.</p>
              <label>Facebook Title</label>
              <%= f.text_field :facebook_title %>
            </div>

            <div class="field clearfix">
              <p class="explanation">The description shown when your site is shared via Facebook.</p>
              <label>Facebook Description</label>
              <%= f.text_area :facebook_description, rows: 2 %>
            </div>

            <div class="field clearfix">
              <p class="explanation">The image shown when your site is shared via facebook. This should have a square aspect ratio and be at least 200px by 200px.</p>
              <label>Facebook Image</label>
              <% if @settings.facebook_image.file? %>
                <%= image_tag @settings.facebook_image.url(:thumb) %><br/>
                <%= f.file_field :facebook_image %><br/>
                <%= f.check_box :facebook_image_delete %><span>Delete current image</span>
              <% else %>
                <%= f.file_field :facebook_image %>
              <% end  %>
            </div>
          </div>

        </fieldset>

        <%= f.submit "Save", :'class' => "btn btn-primary show_loader", :'data-loader' => "project_form" %>
        <span class="loader" data-loader="project_form" style="display:none"></span>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/admin_notification_setup.html.erb
<div id="admin">
  <div class="container content_box clearfix">

    <%= render 'admin/header', active: 'settings' %>

    <div id="admin_notification_setup">

      <div class="main_content">

        <%= form_for(current_user, url: admin_notification_setup_path, html: {method: "put", id: "admin_notification_form"}) do |f| %>

          <fieldset>
            <legend class="foldable"><a>Admin Notifications</a></legend>

            <div class="foldable default_expanded">
              <div class="form-row clearfix">
                <div class="field">
                  <label for="user_wants_admin_payment_notification" class="checkbox">
                    <%= f.check_box 'wants_admin_payment_notification' %>
                    Notify me via email when someone makes a contribution to my campaign
                  </label>
                </div>
              </div>
            </div>

          </fieldset>

          <br />

          <button class="btn btn-primary show_loader" data-loader="bank_form" type="submit">Save</button>
          <span class="loader" data-loader="bank_form" style="display:none"></span>

        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/admin/admin_processor_setup.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'settings' %>

    <ul class="nav nav-tabs nav-processor-setup">
      <li class="active"><a href="<%= admin_processor_setup_path %>">Payment Processor</a></li>
      <li><a href="<%= admin_bank_account_path %>">Bank Setup</a></li>
    </ul>

  <div id="admin_processor_setup">

    <div class="main_content">

      <% if @settings.payments_activated? %>

      <h4>Your payment processor is all set up!</h4>
      <p>Payments can now be activated for your campaigns.  Please make sure to set up your bank account information by clicking the tab above so that you may receive payouts!</p>

      <% else %>

      <%= form_tag(admin_processor_setup_path, method: "post", id: "admin_crowdtilt_form") %>

      <fieldset>
        <p>Tilt Open is set up to use the Tilt API for credit card transactions and bank payouts.  Please contact support.api@Tilt.com to request production Tilt API credentials.</p>

          <div class="form-row clearfix">
            <div class="field">
              <label for="ct_prod_api_key">Tilt Production API Key</label>
              <input name="ct_prod_api_key" id="ct_prod_api_key" type="text" style="width: 320px">
            </div>
          </div>
          <div class="form-row clearfix">
            <div class="field">
              <label for="ct_prod_api_secret">Tilt Production API Secret</label>
              <input name="ct_prod_api_secret" id="ct_prod_api_secret" type="text" style="width: 320px">
            </div>
          </div>

        </fieldset>

        <button class="btn btn-primary show_loader" data-loader="bank_form" type="submit">Save</button>
        <span class="loader" data-loader="bank_form" style="display:none"></span>
      </form>
      <div id="errors"></div>

      <% end %>

    </div>

  </div>
  </div>
</div>

app/views/admin/admin_site_settings.html.erb
<div id="admin">
  <div class="container content_box clearfix">

  <%= render 'admin/header', active: 'settings' %>

    <div id="admin_site_settings">

      <%= form_for(@settings, url: admin_site_settings_path, multipart: true, html: { id: "admin_site_settings_form" }) do |f| %>

        <fieldset>
          <legend class="foldable"><a>Basic Information</a></legend>

          <div class="foldable default_expanded">
            <div class="field clearfix">
              <p class="explanation">This will be used as the page title (for SEO) and the name in the header. Your site name is also what contributors will see on their credit card statements.</p>
              <label>Site Name</label>
              <%= f.text_field :site_name %>
            </div>

            <div class="field clearfix">
              <p class="explanation">Enter an email address where contributors can reach you.</p>
              <label>Reply To Email</label>
              <%= f.text_field :reply_to_email %>
            </div>
            <div class="field clearfix">
              <p class="explanation">Enter a phone number where contributors can reach you.</p>
              <label>Contact Phone Number (Optional)</label>
              <%= f.text_field :phone_number, :placeholder => "555-555-5555" %>
            </div>

            <div class="field clearfix">
              <p class="explanation">If you would like to display a logo instead of your site name in the header, upload it here. Resize the image before uploading for best results in your template.</p>
              <label>Logo</label>
              <% if @settings.logo_image.file? %>
                <%= image_tag @settings.logo_image.url(:thumb) %><br/>
                <%= f.file_field :logo_image %><br/>
                <%= f.check_box :logo_image_delete %><span>Delete current image</span>
              <% else %>
                <%= f.file_field :logo_image %>
              <% end  %>
            </div>

            <div class="field clearfix">
              <p class="explanation">This will place a link in the header to your blog or other such website where you can provide updates. For example, "Updates" could link to "http://myblog.com"</p>
              <label>Header Link</label>
              <label>Link Text</label>
              <%= f.text_field :header_link_text %>
              <label>URL</label>
              <%= f.text_field :header_link_url %>
            </div>
          </div>

        </fieldset>

        <fieldset>
          <legend class="foldable default_expanded"><a>Google Analytics</a></legend>

          <div class="foldable default_expanded">
            <div class="field clearfix">
              <p class="explanation">If would like to add tracking to your site, <a href="http://www.google.com/analytics/" target="_blank">sign up for an account</a>, then paste your tracking ID here.</p>
              <label>Google Analytics ID</label>
              <%= f.text_field :google_id, :placeholder => "UA-0000000-0" %>
            </div>
          </div>

        </fieldset>

        <fieldset>
          <legend class="foldable"><a>Footer Content</a></legend>

          <div class="foldable default_expanded">
            <div class="field clearfix">
              <p class="explanation">The text shown in the footer beside the copyright symbol.</p>
              <label>Copyright Text</label>
              <%= f.text_field :copyright_text %>
            </div>
          </div>

        </fieldset>


        <fieldset>
          <legend class="foldable"><a>Advanced Settings</a></legend>
          <div class="foldable">

            <div class="field clearfix">
              <p class="explanation">Uncheck this box if you would like all campaigns to be private and not appear on search engines like Google.</p>
              <label>Allow search engines to index your Tilt Open site</label>
              <%= f.check_box :indexable %>
            </div>
            <div class="field clearfix">
              <p class="explanation">If you're using a custom domain (eg: campaigns.YourSite.com), you'll need to include a custom Facebook app ID here. Visit https://developers.facebook.com/apps to create a free app for your site.</p>
              <label>Custom Facebook App ID</label>
              <%= f.text_field :facebook_app_id %>
            </div>

          </div>
        </fieldset>

        <%= f.submit "Save", :'class' => "btn btn-primary show_loader", :'data-loader' => "project_form" %>
        <span class="loader" data-loader="project_form" style="display:none"></span>

      <% end %>
    </div>
  </div>
</div>